apiVersion: v1
kind: Secret
metadata:
  name: ddns-config
  namespace: ddns-kubernetes-controller-system
type: Opaque
stringData:
  ddns-config.yaml: |-
    aws:
      AWS_ACCESS_KEY_ID: access-k3y
      AWS_SECRET_ACCESS_KEY: secret-k3y